name: example
description: A simple command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  path: ^1.8.0

  ansi_escapes:
    path: ../
    
dev_dependencies:
  lints: ^6.0.0
